import { lazy } from 'react'

export const ChatPanel = lazy(() => import('../components/ChatPanel'))
export const TemplateModal = lazy(() => import('../components/TemplateModal'))
export const ShareModal = lazy(() => import('../components/ShareModal'))
export const GitPanel = lazy(() => import('../components/GitPanel'))
export const AISettingsModal = lazy(() => import('../components/AISettingsModal'))
export const ImportModal = lazy(() => import('../components/ImportModal'))
export const CollaborationPanel = lazy(() => import('../components/CollaborationPanel'))
export const DiffViewer = lazy(() => import('../components/DiffViewer'))
export const PluginManager = lazy(() => import('../components/PluginManager'))
export const SnippetLibrary = lazy(() => import('../components/SnippetLibrary'))
export const SettingsCenter = lazy(() => import('../components/SettingsCenter'))
export const CommandPalette = lazy(() => import('../components/CommandPalette'))
export const WorkspaceManager = lazy(() => import('../components/WorkspaceManager'))
export const ThemeSelector = lazy(() => import('../components/ThemeSelector'))
export const WelcomeScreen = lazy(() => import('../components/WelcomeScreen'))
export const AuthModal = lazy(() => import('../components/AuthModal'))
export const SubscriptionModal = lazy(() => import('../components/SubscriptionModal'))
export const AgentApplyModal = lazy(() => import('../components/AgentApplyModal').then((m) => ({ default: m.AgentApplyModal })))
